# Clippy configuration for core-term
#
# Based on the style guidelines from STYLE.md
# Configuration for use with:
# `cargo clippy --all-targets --all-features -- -D warnings`

# ---- Function & Module Design ----
# "Functions should generally take fewer than 4 arguments"
# "+1 for self"
too-many-arguments-threshold = 5

# Keep functions and modules reasonably sized
cognitive-complexity-threshold = 20
too-many-lines-threshold = 350
