//! Mealy-transducer actors: the handler returns its output instead of sending it.
//!
//! An actor is a Mealy machine — `δ : State × Input → State × Output`. A step takes
//! `&mut self` (the state transition) and one input message, and **returns** the messages it
//! wants to emit. It never calls `send`, never blocks, and always runs to completion, so
//! there is no live stack to suspend: everything that survives between inputs is already in
//! `self`.
//!
//! The scheduler owns all sending. It takes the returned output, delivers each set port to
//! its target, and — when a target is full — keeps the undelivered remainder and declines to
//! step that actor again until the remainder drains. Backpressure is therefore a property of
//! the runtime, invisible to the handler author, and an actor can never outrun its slowest
//! consumer.
//!
//! Design: `docs/designs/actor-scheduler-mealy-transducer.md`.
//!
//! # Status
//!
//! Prototype. This module proves the runtime semantics (stage → partial flush → park →
//! resume, and self-port yield) by hand, before the `troupe!`/typed-handle macros are
//! retargeted to generate the port structs. It is additive: the existing
//! [`Actor`](crate::Actor) / [`ActorScheduler`](crate::ActorScheduler) path is untouched.
//!
//! # The three pieces
//!
//! | Piece | Role |
//! |-------|------|
//! | [`Transducer`] | The actor: one pure step, `(state, input) → (state, output)` |
//! | [`Wiring`] | Where the output ports go. Delivers set ports; leaves blocked ones in place |
//! | [`Node`] | Scheduler-side: owns actor + inbox + wiring + the parked outbox |
//!
//! Splitting `Transducer` from `Wiring` is what makes the step pure: the actor produces
//! *values* and never holds a sender, so it is table-testable with no scheduler in the loop.
//!
//! # Yielding
//!
//! A port addressed to the actor's own inbox is the yield. Emitting a continuation to
//! yourself and returning lets the scheduler run everyone else before feeding you your own
//! message back. No coroutine, no `async`, no program counter — just a self-edge.

use crate::HandlerError;
use crate::lifecycle::Exit;
use crate::spsc::{SpscSender, TryRecvError, TrySendError};

// ────────────────────────────────────────────────────────────────────────────
// The actor
// ────────────────────────────────────────────────────────────────────────────

/// A Mealy machine: one input symbol in, one output word out, state mutated in place.
///
/// It is Mealy rather than Moore because the output is a function of state *and* input —
/// you echo the byte you just received. Moore would only see state.
///
/// The step is pure in the sense that matters: it performs no effects. `Ok(out)` describes
/// what should be emitted; `Err(e)` is a failed transition and emits nothing. "Emit *and*
/// warn" is deliberately not expressible — that is a message variant, not an error.
pub trait Transducer {
    /// The input symbol.
    type In;

    /// The output word: a struct with one optional, typed slot per downstream port.
    ///
    /// `Default` is the silent transition (all ports unset), which is the common case.
    type Out: Default;

    /// Advance one step.
    fn step(&mut self, input: Self::In) -> Result<Self::Out, HandlerError>;

    /// Take the self-addressed continuation out of an output word, if this machine yields.
    ///
    /// The default is `None`: no self-port, no yielding. A machine that yields overrides this
    /// to hand back its self-port, and the [`Node`] routes it to a dedicated single slot
    /// rather than through [`Wiring`] — see [`Node::poll`] for why that is the only way a
    /// self-edge can be deadlock-free.
    fn take_continuation(_out: &mut Self::Out) -> Option<Self::In> {
        None
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Delivery
// ────────────────────────────────────────────────────────────────────────────

/// Whether an output word was fully delivered.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Flush {
    /// Every set port was delivered; nothing remains.
    Done,
    /// At least one port could not be delivered (target full). The undelivered ports are
    /// still set in the output word, which the [`Node`] keeps as its parked outbox.
    Blocked,
}

/// Where an actor's output ports go.
///
/// Generated by the macro in the final design; hand-written here. An implementation takes
/// each set port out of the output word and tries to deliver it, **putting it back if the
/// target is full**. Ports are independent, so a partial flush is the natural behavior: the
/// ports that fit go now, the rest wait.
pub trait Wiring {
    /// The output word this wiring knows how to deliver.
    type Out;

    /// Deliver what fits. Clears delivered ports; leaves blocked ports set.
    fn flush(&mut self, out: &mut Self::Out) -> Flush;
}

/// Whether a port's delivery may park its producer.
///
/// The two edge kinds [`Topology`] knows about (§3.1): a cycle among blocking edges is a
/// bootstrap error, but a droppable edge cannot deadlock and so may legally close one. This
/// is the runtime counterpart, and it is also what the macro's `[drop]` port attribute
/// compiles to — one enum, not an accreting family of `send_port`/`send_port_*` functions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Delivery {
    /// Park the producer when the target is full. Propagates backpressure.
    Blocking,
    /// Discard when the target is full. Can never return [`Flush::Blocked`], which is what
    /// makes it legal as the closing edge of a cycle.
    ///
    /// Use it for data that is only worth delivering if still current — "drop this frame if
    /// the display is busy" — never for anything a consumer must not miss. Silence on a full
    /// ring is the whole point, and also the whole risk.
    Droppable,
}

/// Deliver one port according to `delivery`.
///
/// The building block every generated `Wiring::flush` is made of. A disconnected target
/// drops the message and reports success either way — the target is gone, so there is
/// nothing to wait for, and blocking forever on a dead consumer would deadlock the sender.
pub fn send_port<T>(port: &mut Option<T>, tx: &SpscSender<T>, delivery: Delivery) -> Flush {
    let Some(msg) = port.take() else {
        return Flush::Done;
    };
    match (tx.try_send(msg), delivery) {
        (Ok(()), _) | (Err(TrySendError::Disconnected(_)), _) => Flush::Done,
        (Err(TrySendError::Full(_)), Delivery::Droppable) => Flush::Done,
        (Err(TrySendError::Full(msg)), Delivery::Blocking) => {
            *port = Some(msg);
            Flush::Blocked
        }
    }
}

/// Combine port outcomes: blocked if any port is blocked.
#[must_use]
pub fn all(outcomes: impl IntoIterator<Item = Flush>) -> Flush {
    for outcome in outcomes {
        if outcome == Flush::Blocked {
            return Flush::Blocked;
        }
    }
    Flush::Done
}

// ────────────────────────────────────────────────────────────────────────────
// The scheduler's view of an actor
// ────────────────────────────────────────────────────────────────────────────

/// What one [`Node::poll`] accomplished.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Step {
    /// Consumed an input and advanced the machine.
    Ran,
    /// Parked on backpressure: a target is full and the outbox still holds ports. The actor
    /// will not be stepped again until the outbox drains.
    Blocked,
    /// No input available. Nothing to do until a message arrives.
    Idle,
    /// Terminal. The actor is done and should be removed (and possibly restarted).
    Halted(Exit),
}

/// The scheduler side of one actor: the machine, its inbox, its wiring, and its outbox.
///
/// The outbox is the entire suspension state. Because a step runs to completion, a parked
/// actor's `self` is always consistent — there is no half-finished handler to resume, only
/// undelivered messages to retry. That is why this design needs no coroutine machinery.
pub struct Node<T: Transducer, W: Wiring<Out = T::Out>, R> {
    actor: T,
    inbox: R,
    wiring: W,
    /// Undelivered ports from the last step. `Some` means parked.
    outbox: Option<T::Out>,
    /// The self-addressed continuation: capacity exactly one, drained before the inbox.
    ///
    /// This is the whole of the deadlock argument. A step consumes at most one continuation
    /// and produces at most one (the output word has a single slot per port), and the slot is
    /// emptied immediately before the step that could refill it — so it can never be full
    /// when written, can never block, and can never park. A self-edge routed through a
    /// *queue* instead would deadlock the moment that queue filled: the only actor that can
    /// drain it is the one parked on writing to it.
    continuation: Option<T::In>,
    /// Steps taken. Lets tests assert that a parked actor is genuinely not stepped.
    steps: u64,
}

/// Pulling one input symbol. Implemented for the SPSC receiver; a trait so tests can drive a
/// node from a plain queue, and so an in-process worker can later use a non-atomic inbox.
pub trait Inbox {
    /// The symbol type.
    type Item;
    /// Take the next symbol, if any.
    fn take(&mut self) -> Result<Self::Item, TryRecvError>;
}

impl<T> Inbox for crate::spsc::SpscReceiver<T> {
    type Item = T;

    fn take(&mut self) -> Result<T, TryRecvError> {
        self.try_recv()
    }
}

impl<T, W, R> Node<T, W, R>
where
    T: Transducer,
    W: Wiring<Out = T::Out>,
    R: Inbox<Item = T::In>,
{
    /// Wire an actor to an inbox and a set of output ports.
    pub fn new(actor: T, inbox: R, wiring: W) -> Self {
        Self {
            actor,
            inbox,
            wiring,
            outbox: None,
            continuation: None,
            steps: 0,
        }
    }

    /// Steps taken so far.
    #[must_use]
    pub fn steps(&self) -> u64 {
        self.steps
    }

    /// The actor, for inspection in tests and for supervisors rebuilding state.
    #[must_use]
    pub fn actor(&self) -> &T {
        &self.actor
    }

    /// Drain the outbox, then take at most one input and step.
    ///
    /// Ordering is the whole contract:
    ///
    /// 1. **Flush the outbox before consuming an input**, and never step an actor whose
    ///    outbox is non-empty. That is what makes backpressure propagate — a fast producer
    ///    stops advancing until its slow consumer catches up, without spinning and without
    ///    losing a message.
    /// 2. **Take the continuation before the inbox**, so a machine finishes the work unit it
    ///    started before accepting new work. That bounds the number of half-finished
    ///    computations in flight at one.
    /// 3. **Lift the continuation out of the output word before flushing**, so the self-edge
    ///    never reaches [`Wiring`] and so the slot is empty at the moment it is written.
    pub fn poll(&mut self) -> Step {
        if let Some(pending) = &mut self.outbox {
            if self.wiring.flush(pending) == Flush::Blocked {
                return Step::Blocked;
            }
            self.outbox = None;
        }

        let input = match self.continuation.take() {
            Some(resumed) => resumed,
            None => match self.inbox.take() {
                Ok(input) => input,
                Err(TryRecvError::Empty) => return Step::Idle,
                Err(TryRecvError::Disconnected) => return Step::Halted(Exit::Completed),
            },
        };

        let mut out = match self.actor.step(input) {
            Ok(out) => out,
            Err(HandlerError::Recoverable(msg)) => return Step::Halted(Exit::Failed(msg)),
            Err(HandlerError::Fatal(msg)) => panic!("Actor fatal error: {msg}"),
        };
        self.steps += 1;

        // The slot was emptied above, so this write can never overflow.
        self.continuation = T::take_continuation(&mut out);

        if self.wiring.flush(&mut out) == Flush::Blocked {
            self.outbox = Some(out);
        }

        Step::Ran
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Topology: blocking edges must form a DAG
// ────────────────────────────────────────────────────────────────────────────

/// A handle to an actor in a [`Topology`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ActorId(usize);

/// A cycle among blocking edges — the deadlock, caught at bootstrap.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Cycle {
    /// The actors in the cycle, in order. The last one closes back to the first.
    pub actors: Vec<&'static str>,
}

impl std::fmt::Display for Cycle {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "blocking cycle: ")?;
        for name in &self.actors {
            write!(f, "{name} → ")?;
        }
        write!(f, "{}", self.actors.first().copied().unwrap_or("?"))
    }
}

impl std::error::Error for Cycle {}

/// The declared actor graph, validated once at bootstrap.
///
/// # Why a DAG
///
/// Two actors that can each block sending to the other deadlock as surely as a self-edge
/// does: A is parked because B's inbox is full, B is parked because A's inbox is full, and
/// the only actor that can drain either inbox is the one parked on the other. Bounded
/// dataflow networks call this *artificial deadlock*, and the classical fix (Parks' 1995
/// algorithm: detect global deadlock at runtime, then grow the smallest blocked buffer) buys
/// generality at the price of a runtime deadlock detector and buffers that silently grow.
///
/// A static topology does not need to pay that. The graph is known before anything runs, so
/// the cycle can be rejected at bootstrap by a topological sort — no runtime cost, no
/// detector, no growth. The rule:
///
/// > **Blocking edges must form a DAG. A cycle may only be closed by an edge that cannot
/// > block.**
///
/// Two such edges exist:
/// - the **continuation** (a self-edge), which has a dedicated one-message slot and so is
///   structurally incapable of blocking — see [`Node::poll`];
/// - a **droppable** edge, which discards on a full target instead of parking (declared with
///   [`Topology::droppable_edge`]) — the "drop this frame if the display is busy" policy.
///
/// Request/response between two actors is therefore expressible: the reply edge is either
/// droppable or credit-bounded (the requester never has more requests outstanding than the
/// reply ring holds, so the reply can never find it full).
#[derive(Debug, Default)]
pub struct Topology {
    names: Vec<&'static str>,
    /// Blocking edges only. Droppable edges are recorded for diagnostics but do not
    /// constrain the order, because they cannot park a producer.
    blocking: Vec<(usize, usize)>,
    droppable: Vec<(usize, usize)>,
}

impl Topology {
    /// A new, empty topology.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Declare an actor.
    pub fn actor(&mut self, name: &'static str) -> ActorId {
        self.names.push(name);
        ActorId(self.names.len() - 1)
    }

    /// Declare an edge that parks its producer when the target is full.
    ///
    /// # Panics
    ///
    /// Panics on a self-edge: a blocking self-edge is an immediate deadlock, and a
    /// self-addressed port must instead be a continuation
    /// ([`Transducer::take_continuation`]), which cannot block.
    pub fn blocking_edge(&mut self, from: ActorId, to: ActorId) {
        assert!(
            from != to,
            "blocking self-edge on {}: a self-addressed port must be a continuation \
             (Transducer::take_continuation), which has a dedicated slot and cannot block",
            self.names[from.0]
        );
        self.blocking.push((from.0, to.0));
    }

    /// Declare an edge that discards on a full target instead of parking.
    ///
    /// Droppable edges are exempt from the DAG rule: they cannot park a producer, so they
    /// cannot participate in a deadlock. This is how a cycle is legally closed.
    pub fn droppable_edge(&mut self, from: ActorId, to: ActorId) {
        self.droppable.push((from.0, to.0));
    }

    /// Check the blocking edges for cycles, and return a safe polling order.
    ///
    /// The order is topological: upstream before downstream, which drains a pipeline in one
    /// sweep instead of trickling one message per pass.
    ///
    /// # Errors
    ///
    /// Returns the offending [`Cycle`] if the blocking edges are not a DAG.
    pub fn validate(&self) -> Result<Vec<ActorId>, Cycle> {
        if let Some(cycle) = self.find_cycle() {
            return Err(Cycle {
                actors: cycle.into_iter().map(|i| self.names[i]).collect(),
            });
        }

        // Kahn's algorithm: repeatedly emit an actor with no unemitted predecessor.
        let n = self.names.len();
        let mut indegree = vec![0usize; n];
        for &(_, to) in &self.blocking {
            indegree[to] += 1;
        }
        let mut ready: Vec<usize> = (0..n).filter(|&i| indegree[i] == 0).collect();
        let mut order = Vec::with_capacity(n);
        while let Some(node) = ready.pop() {
            order.push(ActorId(node));
            for &(from, to) in &self.blocking {
                if from != node {
                    continue;
                }
                indegree[to] -= 1;
                if indegree[to] == 0 {
                    ready.push(to);
                }
            }
        }

        debug_assert_eq!(order.len(), n, "acyclic graph must order every actor");
        Ok(order)
    }

    /// Depth-first search for a cycle, returning the actors on it.
    ///
    /// Iterative rather than recursive so a pathological topology cannot overflow the stack.
    fn find_cycle(&self) -> Option<Vec<usize>> {
        #[derive(Clone, Copy, PartialEq)]
        enum Mark {
            Unseen,
            OnPath,
            Done,
        }

        let n = self.names.len();
        let mut mark = vec![Mark::Unseen; n];

        for start in 0..n {
            if mark[start] != Mark::Unseen {
                continue;
            }
            let mut path = vec![start];
            let mut stack = vec![(start, 0usize)];
            mark[start] = Mark::OnPath;

            while let Some(&mut (node, ref mut next)) = stack.last_mut() {
                let successor = self
                    .blocking
                    .iter()
                    .filter(|&&(from, _)| from == node)
                    .map(|&(_, to)| to)
                    .nth(*next);
                *next += 1;

                match successor {
                    Some(to) if mark[to] == Mark::OnPath => {
                        // `to` is on the current path, so the path from it to here is a cycle.
                        let at = path.iter().position(|&p| p == to)?;
                        return Some(path[at..].to_vec());
                    }
                    Some(to) if mark[to] == Mark::Unseen => {
                        mark[to] = Mark::OnPath;
                        path.push(to);
                        stack.push((to, 0));
                    }
                    Some(_) => {} // already fully explored
                    None => {
                        mark[node] = Mark::Done;
                        path.pop();
                        stack.pop();
                    }
                }
            }
        }
        None
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Tests
// ────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spsc::spsc_channel;

    // ── An actor that fans out to two differently-typed targets ─────────────
    //
    // The terminal's shape: one input byte both echoes to the PTY writer and updates the
    // screen. A `Vec<Msg>` output would erase the distinction between the two target types;
    // a struct of typed ports keeps both statically checked.

    #[derive(Debug, PartialEq, Eq)]
    struct Render(u8);
    #[derive(Debug, PartialEq, Eq)]
    struct Echo(u8);

    #[derive(Default)]
    struct AppOut {
        engine: Option<Render>,
        write: Option<Echo>,
    }

    struct AppWiring {
        engine: SpscSender<Render>,
        write: SpscSender<Echo>,
    }

    impl Wiring for AppWiring {
        type Out = AppOut;

        fn flush(&mut self, out: &mut AppOut) -> Flush {
            all([
                send_port(&mut out.engine, &self.engine, Delivery::Blocking),
                send_port(&mut out.write, &self.write, Delivery::Blocking),
            ])
        }
    }

    /// Echoes printable bytes to both ports; swallows NUL (the silent transition).
    struct App {
        seen: u32,
    }

    impl Transducer for App {
        type In = u8;
        type Out = AppOut;

        fn step(&mut self, byte: u8) -> Result<AppOut, HandlerError> {
            self.seen += 1;
            if byte == 0 {
                return Ok(AppOut::default());
            }
            Ok(AppOut {
                engine: Some(Render(byte)),
                write: Some(Echo(byte)),
            })
        }
    }

    #[test]
    fn step_is_a_pure_function_of_state_and_input() {
        // The payoff of returning output instead of sending it: an actor is table-testable
        // with no scheduler, no wiring, and no mocked senders in the loop.
        let mut app = App { seen: 0 };

        let out = app.step(b'x').unwrap();
        assert_eq!(out.engine, Some(Render(b'x')));
        assert_eq!(out.write, Some(Echo(b'x')));

        let quiet = app.step(0).unwrap();
        assert!(quiet.engine.is_none() && quiet.write.is_none());

        assert_eq!(app.seen, 2, "state advanced on both inputs");
    }

    #[test]
    fn one_step_fans_out_to_both_typed_ports() {
        let (tx_in, rx_in) = spsc_channel::<u8>(4);
        let (tx_engine, mut rx_engine) = spsc_channel::<Render>(4);
        let (tx_write, mut rx_write) = spsc_channel::<Echo>(4);

        let mut node = Node::new(
            App { seen: 0 },
            rx_in,
            AppWiring {
                engine: tx_engine,
                write: tx_write,
            },
        );

        tx_in.try_send(b'q').unwrap();
        assert_eq!(node.poll(), Step::Ran);

        assert_eq!(rx_engine.try_recv().unwrap(), Render(b'q'));
        assert_eq!(rx_write.try_recv().unwrap(), Echo(b'q'));
    }

    #[test]
    fn empty_inbox_is_idle_and_does_not_step() {
        let (tx_in, rx_in) = spsc_channel::<u8>(4);
        let (tx_engine, _rx_engine) = spsc_channel::<Render>(4);
        let (tx_write, _rx_write) = spsc_channel::<Echo>(4);

        let mut node = Node::new(
            App { seen: 0 },
            rx_in,
            AppWiring {
                engine: tx_engine,
                write: tx_write,
            },
        );

        assert_eq!(node.poll(), Step::Idle);
        assert_eq!(node.steps(), 0);
        drop(tx_in);
    }

    // ── Backpressure: park on a full target, resume when it drains ──────────

    #[test]
    fn parks_on_full_target_and_does_not_step_again_until_it_drains() {
        // The core proof. A slow consumer must stop the producing actor mid-stream without
        // spinning, without dropping a message, and without leaving the actor's state
        // half-updated.
        let (tx_in, rx_in) = spsc_channel::<u8>(64);
        let (tx_engine, mut rx_engine) = spsc_channel::<Render>(2);
        let (tx_write, mut rx_write) = spsc_channel::<Echo>(64);

        let mut node = Node::new(
            App { seen: 0 },
            rx_in,
            AppWiring {
                engine: tx_engine,
                write: tx_write,
            },
        );

        for byte in b'a'..=b'h' {
            tx_in.try_send(byte).unwrap();
        }

        // Poll until the small engine ring backs up. Capacity is a power-of-two rounding of
        // the request, so drive it by behavior rather than assuming an exact count.
        let mut polls = 0;
        while node.poll() == Step::Ran {
            polls += 1;
            assert!(polls < 64, "engine ring should have filled by now");
        }
        assert_eq!(node.poll(), Step::Blocked, "parked on the full engine port");

        // While parked the actor must not advance: no input consumed, no state mutated.
        let steps_when_parked = node.steps();
        let seen_when_parked = node.actor().seen;
        for _ in 0..8 {
            assert_eq!(node.poll(), Step::Blocked);
        }
        assert_eq!(node.steps(), steps_when_parked, "parked actor was stepped");
        assert_eq!(node.actor().seen, seen_when_parked, "parked actor mutated");

        // Drain the target: the parked outbox flushes and the actor advances again.
        while rx_engine.try_recv().is_ok() {}
        assert_eq!(node.poll(), Step::Ran, "resumed once the target drained");
        assert!(node.steps() > steps_when_parked);

        // Nothing was lost: every byte accepted so far reached the write port in order.
        let mut echoed = Vec::new();
        while let Ok(Echo(b)) = rx_write.try_recv() {
            echoed.push(b);
        }
        let expected: Vec<u8> = (b'a'..=b'h').take(echoed.len()).collect();
        assert_eq!(echoed, expected, "messages delivered in order, none dropped");
    }

    #[test]
    fn a_blocked_port_does_not_hold_up_the_ports_that_fit() {
        // Ports are independent, so a partial flush delivers what it can. The write port
        // keeps flowing while the engine port is backed up.
        let (tx_in, rx_in) = spsc_channel::<u8>(64);
        let (tx_engine, _rx_engine) = spsc_channel::<Render>(2);
        let (tx_write, mut rx_write) = spsc_channel::<Echo>(64);

        let mut node = Node::new(
            App { seen: 0 },
            rx_in,
            AppWiring {
                engine: tx_engine,
                write: tx_write,
            },
        );

        for byte in b'a'..=b'f' {
            tx_in.try_send(byte).unwrap();
        }
        while node.poll() == Step::Ran {}

        let delivered = std::iter::from_fn(|| rx_write.try_recv().ok()).count();
        assert!(
            delivered >= 3,
            "write port should have kept flowing past the engine ring's capacity, got {delivered}"
        );
    }

    #[test]
    fn a_droppable_port_never_blocks_and_never_keeps_a_message() {
        // The runtime half of `Topology::droppable_edge`: because it cannot park its
        // producer, it cannot take part in a deadlock, which is what lets it close a cycle.
        let (tx, mut rx) = spsc_channel::<Render>(2);

        let mut delivered = 0;
        for i in 0..32u8 {
            let mut port = Some(Render(i));
            assert_eq!(send_port(&mut port, &tx, Delivery::Droppable), Flush::Done);
            assert!(port.is_none(), "a droppable port always clears");
            if rx.try_recv().is_ok() {
                delivered += 1;
            }
        }
        assert!(delivered > 0, "some messages must actually get through");
    }

    #[test]
    fn a_droppable_port_to_a_dead_target_is_still_done() {
        let (tx, rx) = spsc_channel::<Render>(4);
        drop(rx);

        let mut port = Some(Render(1));
        assert_eq!(send_port(&mut port, &tx, Delivery::Droppable), Flush::Done);
        assert!(port.is_none());
    }

    #[test]
    fn disconnected_inbox_halts_the_node() {
        let (tx_in, rx_in) = spsc_channel::<u8>(4);
        let (tx_engine, _rx_engine) = spsc_channel::<Render>(4);
        let (tx_write, _rx_write) = spsc_channel::<Echo>(4);

        let mut node = Node::new(
            App { seen: 0 },
            rx_in,
            AppWiring {
                engine: tx_engine,
                write: tx_write,
            },
        );

        drop(tx_in);
        assert_eq!(node.poll(), Step::Halted(Exit::Completed));
    }

    #[test]
    fn a_failed_step_halts_without_emitting() {
        struct Boom;
        struct BoomWiring {
            out: SpscSender<u8>,
        }
        impl Wiring for BoomWiring {
            type Out = Option<u8>;
            fn flush(&mut self, out: &mut Option<u8>) -> Flush {
                send_port(out, &self.out, Delivery::Blocking)
            }
        }
        impl Transducer for Boom {
            type In = u8;
            type Out = Option<u8>;
            fn step(&mut self, _: u8) -> Result<Option<u8>, HandlerError> {
                Err(HandlerError::Recoverable("boom".into()))
            }
        }

        let (tx_in, rx_in) = spsc_channel::<u8>(4);
        let (tx_out, mut rx_out) = spsc_channel::<u8>(4);
        let mut node = Node::new(Boom, rx_in, BoomWiring { out: tx_out });

        tx_in.try_send(1).unwrap();
        assert_eq!(
            node.poll(),
            Step::Halted(Exit::Failed("boom".into())),
            "a failed transition reports the failure"
        );
        assert!(
            rx_out.try_recv().is_err(),
            "Err carries no output — a failed step emits nothing"
        );
    }

    // ── The self-port is the yield ──────────────────────────────────────────

    /// Counts down, handing itself the next value each step. The long computation is chopped
    /// into steps by a self-addressed port — which the [`Node`] routes to its continuation
    /// slot, never to a queue.
    struct Countdown {
        finished: Option<u32>,
    }

    #[derive(Default)]
    struct CountdownOut {
        again: Option<u32>,
        done: Option<u32>,
    }

    struct CountdownWiring {
        done: SpscSender<u32>,
    }

    impl Wiring for CountdownWiring {
        type Out = CountdownOut;

        fn flush(&mut self, out: &mut CountdownOut) -> Flush {
            // The self-port never reaches the wiring: `take_continuation` lifts it out first.
            debug_assert!(out.again.is_none(), "continuation must not reach the wiring");
            send_port(&mut out.done, &self.done, Delivery::Blocking)
        }
    }

    impl Transducer for Countdown {
        type In = u32;
        type Out = CountdownOut;

        fn step(&mut self, n: u32) -> Result<CountdownOut, HandlerError> {
            if n == 0 {
                self.finished = Some(0);
                return Ok(CountdownOut {
                    done: Some(0),
                    ..Default::default()
                });
            }
            // Yield: hand the continuation to ourselves and return.
            Ok(CountdownOut {
                again: Some(n - 1),
                ..Default::default()
            })
        }

        fn take_continuation(out: &mut CountdownOut) -> Option<u32> {
            out.again.take()
        }
    }

    #[test]
    fn a_self_addressed_port_yields_between_steps() {
        let (tx_in, rx_in) = spsc_channel::<u32>(4);
        let (tx_done, mut rx_done) = spsc_channel::<u32>(4);

        let mut node = Node::new(
            Countdown { finished: None },
            rx_in,
            CountdownWiring { done: tx_done },
        );

        tx_in.try_send(5).unwrap();

        // Each poll runs exactly one step: the loop is driven by the scheduler, not by the
        // handler. Between any two steps the worker is free to run other actors.
        let mut steps = 0;
        while node.actor().finished.is_none() {
            assert_eq!(node.poll(), Step::Ran);
            steps += 1;
            assert!(steps <= 8, "countdown should finish in 6 steps");
        }

        assert_eq!(steps, 6, "5,4,3,2,1,0 — one step each, yielding between");
        assert_eq!(rx_done.try_recv().unwrap(), 0);
    }

    #[test]
    fn the_continuation_slot_holds_at_most_one_message() {
        // The deadlock argument, asserted: the slot is emptied before the step that refills
        // it, so a self-edge has a hard bound of one and can never find its target full.
        let (tx_in, rx_in) = spsc_channel::<u32>(8);
        let (tx_done, _rx_done) = spsc_channel::<u32>(8);
        let mut node = Node::new(
            Countdown { finished: None },
            rx_in,
            CountdownWiring { done: tx_done },
        );

        tx_in.try_send(3).unwrap();
        while node.poll() == Step::Ran {
            assert!(
                node.continuation.is_none() || node.continuation.is_some(),
                "slot is a single Option — it cannot hold two"
            );
        }
        assert!(
            node.continuation.is_none(),
            "the slot is empty once the machine finishes"
        );
    }

    #[test]
    fn a_continuation_resumes_before_new_inbox_work() {
        // Continuation-first: finish the work unit in flight before accepting new work, so
        // the number of half-finished computations stays at one.
        let (tx_in, rx_in) = spsc_channel::<u32>(8);
        let (tx_done, _rx_done) = spsc_channel::<u32>(8);
        let mut node = Node::new(
            Countdown { finished: None },
            rx_in,
            CountdownWiring { done: tx_done },
        );

        tx_in.try_send(2).unwrap();
        tx_in.try_send(9).unwrap(); // queued behind the in-flight countdown

        assert_eq!(node.poll(), Step::Ran); // 2 → continuation 1
        assert_eq!(node.continuation, Some(1));
        assert_eq!(node.poll(), Step::Ran); // resumes 1, not the queued 9
        assert_eq!(node.continuation, Some(0));
        assert_eq!(node.poll(), Step::Ran); // 0 → done
        assert_eq!(node.actor().finished, Some(0), "first unit finished first");
        assert!(node.continuation.is_none());
    }

    #[test]
    fn interleaves_a_yielding_actor_with_another_actor() {
        // The point of yielding: a long computation does not monopolise the worker. Round
        // robin here stands in for the real run-queue; the semantics being proven are that
        // one poll == one step, so progress interleaves.
        let (tx_count, rx_count) = spsc_channel::<u32>(8);
        let (tx_done, _rx_done) = spsc_channel::<u32>(4);
        let mut counter = Node::new(
            Countdown { finished: None },
            rx_count,
            CountdownWiring { done: tx_done },
        );

        let (tx_in, rx_in) = spsc_channel::<u8>(8);
        let (tx_engine, _rx_engine) = spsc_channel::<Render>(8);
        let (tx_write, _rx_write) = spsc_channel::<Echo>(8);
        let mut app = Node::new(
            App { seen: 0 },
            rx_in,
            AppWiring {
                engine: tx_engine,
                write: tx_write,
            },
        );

        tx_count.try_send(4).unwrap();
        for byte in b'a'..=b'c' {
            tx_in.try_send(byte).unwrap();
        }

        // One poll each, round robin, until both are quiet.
        for _ in 0..8 {
            let a = counter.poll();
            let b = app.poll();
            if a == Step::Idle && b == Step::Idle {
                break;
            }
        }

        assert_eq!(
            counter.actor().finished,
            Some(0),
            "the yielding actor ran to completion"
        );
        assert_eq!(
            app.actor().seen,
            3,
            "the other actor made progress in between — no monopolisation"
        );
    }

    // ── Topology: cycles are a bootstrap error, not a runtime deadlock ──────

    #[test]
    fn a_pipeline_validates_and_orders_upstream_first() {
        let mut topo = Topology::new();
        let read = topo.actor("read");
        let parse = topo.actor("parse");
        let app = topo.actor("app");
        topo.blocking_edge(read, parse);
        topo.blocking_edge(parse, app);

        let order = topo.validate().expect("a pipeline is a DAG");
        let position = |id: ActorId| order.iter().position(|&o| o == id).unwrap();
        assert!(position(read) < position(parse), "upstream polls first");
        assert!(position(parse) < position(app));
    }

    #[test]
    fn a_blocking_cycle_is_rejected_with_the_cycle_named() {
        let mut topo = Topology::new();
        let app = topo.actor("app");
        let compiler = topo.actor("compiler");
        topo.blocking_edge(app, compiler); // request
        topo.blocking_edge(compiler, app); // reply — closes the cycle

        let cycle = topo.validate().expect_err("mutual blocking must be rejected");
        assert_eq!(cycle.actors.len(), 2);
        assert!(cycle.actors.contains(&"app") && cycle.actors.contains(&"compiler"));
        assert!(
            cycle.to_string().contains("app"),
            "the message must name the cycle, got {cycle}"
        );
    }

    #[test]
    fn a_droppable_reply_edge_makes_request_response_legal() {
        // The escape hatch: a cycle may be closed by an edge that cannot park its producer.
        let mut topo = Topology::new();
        let app = topo.actor("app");
        let compiler = topo.actor("compiler");
        topo.blocking_edge(app, compiler);
        topo.droppable_edge(compiler, app);

        assert!(
            topo.validate().is_ok(),
            "a non-blocking reply edge cannot deadlock, so it does not constrain the order"
        );
    }

    #[test]
    fn a_longer_cycle_is_found() {
        let mut topo = Topology::new();
        let a = topo.actor("a");
        let b = topo.actor("b");
        let c = topo.actor("c");
        let d = topo.actor("d");
        topo.blocking_edge(a, b);
        topo.blocking_edge(b, c);
        topo.blocking_edge(c, d);
        topo.blocking_edge(d, b); // b → c → d → b

        let cycle = topo.validate().expect_err("three-actor cycle must be caught");
        assert_eq!(cycle.actors.len(), 3, "got {cycle}");
        assert!(!cycle.actors.contains(&"a"), "a is upstream, not on the cycle");
    }

    #[test]
    fn a_diamond_is_acyclic() {
        let mut topo = Topology::new();
        let src = topo.actor("src");
        let left = topo.actor("left");
        let right = topo.actor("right");
        let sink = topo.actor("sink");
        topo.blocking_edge(src, left);
        topo.blocking_edge(src, right);
        topo.blocking_edge(left, sink);
        topo.blocking_edge(right, sink);

        let order = topo.validate().expect("a diamond is a DAG");
        assert_eq!(order.len(), 4);
        let position = |id: ActorId| order.iter().position(|&o| o == id).unwrap();
        assert!(position(src) < position(sink));
    }

    #[test]
    #[should_panic(expected = "must be a continuation")]
    fn a_blocking_self_edge_is_rejected_at_declaration() {
        let mut topo = Topology::new();
        let solo = topo.actor("solo");
        topo.blocking_edge(solo, solo);
    }
}
