# Clippy configuration for core-term
#
# Baseline transcribed from STYLE.MD and direct user feedback,
# now with additions based on the ethos of STYLE.MD.
#
# Assumes the baseline command:
# `cargo clippy --all-targets --all-features -- -D warnings`

# ---- Baseline from STYLE.MD Directives ----
unwrap_used = "deny"
expect_used = "deny"

# ---- Magic Numbers (STYLE.MD: Section 1) ----
# "Avoid using literal numbers other than 0, 1, or 2 directly in the code... Define `const`ants..."
unreadable_literal = "deny"

missing-docs-in-private-items = "deny"

cyclomatic_complexity_threshold = 15
too_many_lines_threshold = 350
too_many_arguments_threshold = 4

module_name_repetitions = "allow"

print_stdout = "allow"
print_stderr = "allow"

# ---- Additions Based on STYLE.MD Ethos (Clarity, Simplicity, Robustness) ----

# --- Enhancing Robustness and Deliberate Design ---
# STYLE.MD: "Error Handling", "Magic Numbers", "unsafe Code"

# Pedantic lints that improve safety related to numeric casts,
# aligning with avoiding hidden complexities or implicit behaviors.
cast_possible_truncation = "deny" # Was allow by default (pedantic group)
cast_possible_wrap = "deny"       # Was allow by default (pedantic group)
cast_precision_loss = "deny"      # Was allow by default (pedantic group)
cast_sign_loss = "deny"           # Was allow by default (pedantic group)

# Encourages adding `#[must_use]` to functions that compute a value without side effects.
# This promotes explicitness in how return values are handled.
must_use_candidate = "deny" # Was allow by default (pedantic group)

# Prefer `TryFrom` for fallible conversions over a `From` impl that might panic or lose error info.
fallible_impl_from = "deny" # Was allow by default (pedantic group)

# Helps catch incorrect unsafe patterns by ensuring raw pointer arguments are in `unsafe fn`.
not_unsafe_ptr_arg_deref = "deny" # Was allow by default (pedantic group)

