// src/backends/mod.rs

//! Defines the `Driver` trait for backend implementations (e.g., X11, console)
//! and common types used by backends and the renderer, such as `BackendEvent`,
//! `CellCoords`, `TextRunStyle`, and `CellRect`.

// Import Color directly from the color module, not via glyph.
use crate::color::Color;
use crate::glyph::AttrFlags; // AttrFlags is correctly in glyph.
use anyhow::Result;
use std::os::unix::io::RawFd;

// Re-export driver implementations so they can be accessed via `crate::backends::console::ConsoleDriver`, etc.
pub mod console;
pub mod x11;

// It can be useful to re-export concrete driver types if they are frequently
// used directly by `main.rs` or other high-level modules, though this is optional.
// Example:
// pub use console::ConsoleDriver;
// pub use x11::XDriver;

// --- Public Constants ---
// Default character dimensions for the terminal window.
// These are used if a backend cannot determine them from the environment
// or for initial setup before full font metrics are available.
pub const DEFAULT_WINDOW_WIDTH_CHARS: usize = 80;
pub const DEFAULT_WINDOW_HEIGHT_CHARS: usize = 24;

/// Represents events originating from the backend (platform-specific UI/input).
/// These events are processed by the `AppOrchestrator`, which may then update the
/// `TerminalEmulator` or perform other actions like writing to the PTY.
#[derive(Debug, Clone, PartialEq, Eq)] // Added Eq for full PartialEq comparison if needed by event handlers
pub enum BackendEvent {
    /// A keyboard key was pressed.
    Key {
        /// Platform-specific key symbol (e.g., X11 KeySym, or an abstract representation).
        keysym: u32,
        /// Text generated by the key event (e.g., from XLookupString or similar IME output).
        /// This can be empty if the key press does not produce a printable character (e.g., modifier keys).
        text: String,
    },
    /// The window or display area was resized by the platform.
    /// Provides new dimensions in pixels. The orchestrator uses these
    /// along with font metrics to calculate new cell dimensions for the terminal.
    Resize {
        /// New width of the display area in pixels.
        width_px: u16,
        /// New height of the display area in pixels.
        height_px: u16,
    },
    /// The application received a request to close from the platform
    /// (e.g., user clicked the window's close button).
    CloseRequested,
    /// The terminal window gained input focus.
    FocusGained,
    /// The terminal window lost input focus.
    FocusLost,
}

/// Defines coordinates for a single character cell on the terminal grid (0-based).
#[derive(Debug, Clone, Copy, PartialEq, Eq)] // Added Eq
pub struct CellCoords {
    /// 0-based column index (x-coordinate).
    pub x: usize,
    /// 0-based row index (y-coordinate).
    pub y: usize,
}

/// Defines the visual style (colors and attribute flags) for a run of text.
/// This struct is used by the `Renderer` to instruct the `Driver` on how to draw text.
#[derive(Debug, Clone, Copy, PartialEq, Eq)] // Added Eq
pub struct TextRunStyle {
    /// Foreground color for the text. Expected to be a concrete color by the driver.
    pub fg: Color,
    /// Background color for the text. Expected to be a concrete color by the driver.
    pub bg: Color,
    /// Attribute flags (e.g., bold, underline) for the text.
    pub flags: AttrFlags,
}

/// Defines a rectangular area of cells on the terminal grid.
/// Uses 0-based coordinates, and width/height are in number of cells.
#[derive(Debug, Clone, Copy, PartialEq, Eq)] // Added Eq
pub struct CellRect {
    /// 0-based column index of the top-left corner of the rectangle.
    pub x: usize,
    /// 0-based row index of the top-left corner of the rectangle.
    pub y: usize,
    /// Width of the rectangle in character cells.
    pub width: usize,
    /// Height of the rectangle in character cells.
    pub height: usize,
}

/// Defines the interface for a rendering and platform interaction driver.
///
/// A `Driver` is responsible for:
/// 1.  Window and display setup and management (e.g., creating an X11 window or setting up the console).
/// 2.  Handling platform-specific events (input, resize, close requests) and
///     translating them into generic `BackendEvent`s.
/// 3.  Providing an event source (e.g., a file descriptor) that the main event loop can monitor.
/// 4.  Implementing abstract drawing primitives that the `Renderer` uses to draw the
///     terminal state without needing to know backend-specific details.
/// 5.  Providing font and display metrics (character cell size, total display size in pixels).
/// 6.  Handling other platform-specific operations like setting the window title or ringing the bell.
pub trait Driver {
    /// Creates and initializes a new driver instance.
    ///
    /// This method should perform all necessary setup for the backend, such as
    /// opening display connections, creating windows, or configuring the console.
    /// Initial dimensions might be hints or determined by the driver itself.
    ///
    /// # Returns
    /// * `Result<Self>` where `Self` is `Sized`: The initialized driver instance or an error if setup fails.
    fn new() -> Result<Self>
    where
        Self: Sized;

    /// Returns an optional raw file descriptor that the orchestrator can monitor
    /// (e.g., using `epoll` or `select`) for platform events.
    ///
    /// If the driver uses a different event notification mechanism or polls internally,
    /// it can return `None`.
    fn get_event_fd(&self) -> Option<RawFd>;

    /// Processes any pending platform events.
    ///
    /// This method should be called when `get_event_fd()` indicates activity,
    /// or periodically if no FD is provided (polling). It translates native
    /// platform events (like X11 events or console input) into a list of
    /// generic `BackendEvent`s for the orchestrator to handle.
    ///
    /// # Returns
    /// * `Result<Vec<BackendEvent>>`: A vector of `BackendEvent`s that occurred,
    ///   or an error if event processing failed critically.
    fn process_events(&mut self) -> Result<Vec<BackendEvent>>;

    /// Retrieves the dimensions of a single character cell in pixels.
    ///
    /// # Returns
    /// A tuple `(width_px, height_px)` representing the width and height of a character cell.
    fn get_font_dimensions(&self) -> (usize, usize);

    /// Retrieves the current dimensions of the display area managed by this driver, in pixels.
    /// This typically corresponds to the client area of a window or the full console dimensions.
    ///
    /// # Returns
    /// A tuple `(width_px, height_px)` representing the total display width and height in pixels.
    fn get_display_dimensions_pixels(&self) -> (u16, u16);

    // --- Abstract Drawing Primitives ---
    // These methods are called by the Renderer to draw the terminal.
    // The `Color` arguments for drawing (e.g., `bg` in `clear_all`, `style.fg`, `style.bg`
    // in `draw_text_run`, `color` in `fill_rect`) are guaranteed by the Renderer
    // to be concrete colors (i.e., not `Color::Default`). The Driver implements
    // the actual drawing using these concrete colors.

    /// Clears the entire display area with the specified background color.
    /// This is typically called at the beginning of a full redraw.
    ///
    /// # Arguments
    /// * `bg`: The concrete `Color` to fill the entire display area with.
    fn clear_all(&mut self, bg: Color) -> Result<()>;

    /// Draws a run of text characters at a given cell coordinate with a specified style.
    ///
    /// # Arguments
    /// * `coords`: The `CellCoords` (0-based column, row) where the text run begins.
    /// * `text`: The string of characters to draw. These are Unicode characters.
    ///           The driver should handle rendering them appropriately with its font.
    ///           The `Renderer` handles wide characters by drawing the character in the first
    ///           cell and ensuring the second cell (placeholder) is cleared or handled correctly.
    /// * `style`: The `TextRunStyle` (concrete foreground color, concrete background color, attribute flags) for the text.
    fn draw_text_run(&mut self, coords: CellCoords, text: &str, style: TextRunStyle) -> Result<()>;

    /// Fills a rectangular area of cells with a specified concrete color.
    /// This is typically used for clearing parts of lines or drawing backgrounds for text runs.
    ///
    /// # Arguments
    /// * `rect`: The `CellRect` (top-left x, y, width, height in cells) defining the area to fill.
    /// * `color`: The concrete `Color` to fill the rectangle with.
    fn fill_rect(&mut self, rect: CellRect, color: Color) -> Result<()>;

    /// Presents the composed frame to the display.
    /// For double-buffered systems, this would typically swap the buffers.
    /// For other systems (like a console driver), it might flush an output stream.
    fn present(&mut self) -> Result<()>;

    // --- Additional Driver Capabilities ---

    /// Sets the window title for graphical backends.
    /// For console backends, this might be a no-op or use an OSC sequence.
    fn set_title(&mut self, title: &str);

    /// Rings the terminal bell (audible or visual).
    fn bell(&mut self);

    /// Sets the visibility of the cursor for the backend.
    /// `true` to show the cursor, `false` to hide it.
    fn set_cursor_visibility(&mut self, visible: bool);

    /// Informs the driver about focus changes.
    /// `true` if the terminal gained focus, `false` if it lost focus.
    /// This can be used by the driver to change cursor appearance (e.g., solid vs. hollow).
    fn set_focus(&mut self, focused: bool);

    /// Performs any necessary cleanup before the driver is dropped.
    /// This includes releasing platform resources (e.g., closing display connections,
    /// restoring terminal modes). This method should be idempotent.
    fn cleanup(&mut self) -> Result<()>;
}
