// src/term/action.rs

//! Defines actions that the terminal emulator signals to the orchestrator.
//! These actions represent side effects or requests for external system
//! interactions based on the processed terminal inputs.

/// Actions that the terminal emulator signals to the orchestrator.
///
/// These are produced by the `TerminalEmulator` after interpreting input
/// and represent tasks for the main application loop (orchestrator) to perform.
#[derive(Debug, Clone, PartialEq)]
pub enum EmulatorAction {
    /// Request to write the given bytes to the PTY (Pseudo-Terminal).
    /// This typically contains user input or responses generated by the terminal.
    WritePty(Vec<u8>),

    /// Request to set the terminal window's title.
    SetTitle(String),

    /// Request to ring the terminal bell.
    RingBell,

    /// Signal that some part of the terminal display has changed and a redraw
    /// by the renderer is likely needed.
    RequestRedraw,

    /// Request to set the visibility of the (potentially native) cursor by the driver.
    SetCursorVisibility(bool),

    /// Request to copy the given string to the system clipboard.
    CopyToClipboard(String),

    /// Request to fetch content from the system clipboard.
    /// The orchestrator should respond with a `UserInputAction::PasteText`
    /// if content is available.
    RequestClipboardContent,
}
