// src/term/action.rs

//! Defines actions and events used within the terminal emulator module.
//! This includes user-initiated actions, control events, and actions
//! the emulator signals to the orchestrator.

use crate::platform::backends::{KeySymbol, Modifiers}; // Assuming these are re-exported via backends
use serde::{Deserialize, Serialize};

// --- User Input Actions ---

/// Represents user-initiated actions that serve as input to the terminal emulator.
/// This corresponds to `EmulatorInput::User(UserInputAction)`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)] // Eq might be tricky if text is String
pub enum UserInputAction {
    KeyInput {
        symbol: KeySymbol,
        modifiers: Modifiers,
        text: Option<String>, // Text from IME or key press, if any
    },
    // MouseInput variant removed as per new design for selection actions
    InitiateCopy, // This might be used for explicit copy commands (e.g., Ctrl+Shift+C)
    // InitiatePaste, // This will be replaced by RequestClipboardPaste / RequestPrimaryPaste
    FocusGained,
    FocusLost,
    PasteText(String), // Content from clipboard to be pasted by orchestrator

    // New selection-related actions
    /// Starts a selection at the given cell coordinates (e.g., mouse button press).
    StartSelection {
        x: usize,
        y: usize,
    },
    /// Extends an ongoing selection to the given cell coordinates (e.g., mouse drag).
    ExtendSelection {
        x: usize,
        y: usize,
    },
    /// Finalizes a selection (e.g., mouse button release).
    /// If the selection start and end are the same (a click without drag),
    /// it might clear any existing selection or perform other click-based actions.
    ApplySelectionClear,
    /// Requests the orchestrator to paste content from the system clipboard.
    RequestClipboardPaste,
    /// Requests the orchestrator to paste content from the primary selection (X11 specific).
    RequestPrimaryPaste,

    // Application-level actions
    RequestQuit,
    RequestZoomIn,
    RequestZoomOut,
    RequestZoomReset,
    RequestToggleFullscreen,
    RequestScrollLineUp,
    RequestScrollLineDown,
    RequestScrollPageUp,
    RequestScrollPageDown,
    RequestScrollToTop,
    RequestScrollToBottom,
    // Other user-driven actions can be added here.
}

// --- Emulator Control Events ---

/// Represents internal control events for the terminal emulator.
#[derive(Debug)]
pub enum ControlEvent {
    /// Request for the orchestrator to generate a snapshot for rendering.
    /// Sent by Vsync or when user input requires immediate visual feedback.
    RequestSnapshot,
    /// Returns a rendered snapshot back to the orchestrator for reuse.
    /// The Platform sends this after rendering to return the snapshot buffer.
    FrameRendered(Box<crate::term::snapshot::RenderSnapshot>),
    /// Signals a resize of the terminal display area.
    Resize { cols: usize, rows: usize },
}

// --- Emulator Actions (Signaled to Orchestrator) ---

/// Actions that the terminal emulator signals to the orchestrator.
///
/// These are produced by the `TerminalEmulator` after interpreting input
/// and represent tasks for the main application loop (orchestrator) to perform.
#[derive(Debug, Clone, PartialEq)]
pub enum EmulatorAction {
    /// Request to write the given bytes to the PTY (Pseudo-Terminal).
    /// This typically contains user input or responses generated by the terminal.
    WritePty(Vec<u8>),

    /// Request to set the terminal window's title.
    SetTitle(String),

    /// Request to ring the terminal bell.
    RingBell,

    /// Signal that some part of the terminal display has changed and a redraw
    /// by the renderer is likely needed.
    RequestRedraw,
    // Keeping it for now as it's a common signal.
    /// Request to set the visibility of the (potentially native) cursor by the driver.
    SetCursorVisibility(bool),

    /// Request to copy the provided text to the system clipboard.
    CopyToClipboard(String),

    /// Request for the orchestrator to fetch content from the system clipboard.
    /// The orchestrator should then feed this back via `EmulatorInput::User(UserInputAction::PasteText(...))`.
    RequestClipboardContent,

    /// Request to resize the PTY to match the terminal dimensions.
    /// This is sent when ANSI sequences request a terminal resize.
    ResizePty { cols: u16, rows: u16 },
}
