// src/term/mod.rs

//! This module defines the core terminal emulator logic, including input handling,
//! state representation, and actions for external interaction. It serves as the
//! primary interface for the terminal's state machine.

// Sub-modules - existing and new
pub mod cursor;
pub mod screen;
pub mod unicode;

pub mod action;
pub mod charset;
mod emulator;
pub mod modes;

// Re-export items for easier use by other modules and within this module
pub use action::EmulatorAction;
pub use charset::{map_to_dec_line_drawing, CharacterSet};
pub use emulator::TerminalEmulator;
pub use modes::{DecModeConstant, DecPrivateModes, EraseMode, Mode};

// Crate-level imports
use crate::{
    ansi::commands::AnsiCommand,
    backends::{BackendEvent, MouseButton, MouseEventType},
    config::{KeySymbol, Modifiers},
    glyph::Glyph,
    term::cursor::{CursorController, ScreenContext},
    term::screen::Screen,
};

/// Default interval for tab stops, in character cells.
pub const DEFAULT_TAB_INTERVAL: u8 = 8;
/// Default shape code for the terminal cursor (e.g., 2 for block).
pub(crate) const DEFAULT_CURSOR_SHAPE: u16 = 2;

/// Internal control events for the `TerminalEmulator`.
/// These events are typically generated by the orchestrator or other parts of the
/// application to signal changes or requests to the terminal core.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ControlEvent {
    /// Indicates that a frame has been rendered to the display.
    /// This can be used by the emulator for synchronization or state updates post-render.
    FrameRendered,
    /// Signals that the terminal display area has been resized.
    /// `cols` and `rows` are the new dimensions in character cells.
    Resize { cols: usize, rows: usize },
}

/// Inputs that the terminal emulator processes.
///
/// This enum encapsulates the different kinds of data or events
/// that the `TerminalEmulator` can receive and act upon. It serves as the
/// primary "instruction set" for the terminal's internal state machine.
#[derive(Debug, Clone, PartialEq)]
pub enum EmulatorInput {
    /// An ANSI command or sequence parsed from the output of the
    /// program running in the PTY (Pseudo-Terminal).
    Ansi(AnsiCommand),

    /// An action initiated by the user, typically translated from a backend event
    /// (e.g., keyboard input, mouse click) or an internal request (e.g., paste).
    User(UserInputAction),
    /// An internal control event, such as a resize notification from the orchestrator
    /// or a post-render signal.
    Control(ControlEvent),

    /// A single raw character. This variant is typically used for direct character
    /// printing without full ANSI processing. For consistency, most character data
    /// should be wrapped in `AnsiCommand::Print` and sent as `EmulatorInput::Ansi`.
    RawChar(char),
}

/// User-initiated actions, often translated from backend events or internal logic,
/// that the terminal emulator needs to process.
#[derive(Debug, Clone, PartialEq)]
pub enum UserInputAction {
    /// Represents a key press by the user.
    KeyInput {
        /// The symbolic representation of the key (e.g., `KeySymbol::Char('a')`, `KeySymbol::Return`).
        symbol: KeySymbol,
        /// Active keyboard modifiers (e.g., Ctrl, Shift, Alt).
        modifiers: Modifiers,
        /// Optional text generated by the key press, especially relevant for IMEs
        /// or complex key combinations. `None` if the key press does not produce text.
        text: Option<String>,
    },
    /// Represents a mouse event.
    MouseInput {
        /// The type of mouse event (e.g., Press, Release, Move).
        event_type: MouseEventType,
        /// 0-based column of the mouse event, in character cells.
        col: usize,
        /// 0-based row of the mouse event, in character cells.
        row: usize,
        /// The mouse button involved in the event.
        button: MouseButton,
        /// Active keyboard modifiers at the time of the mouse event.
        modifiers: Modifiers,
    },
    /// A user request to initiate a copy operation (e.g., from a keybinding or menu).
    /// The terminal should respond by taking its current selection and producing
    /// an `EmulatorAction::CopyToClipboard`.
    InitiateCopy,
    /// A user request to initiate a paste operation (e.g., from a keybinding or menu).
    /// The terminal should respond by producing an `EmulatorAction::RequestClipboardContent`.
    InitiatePaste,
    /// Clipboard content received (e.g., from the orchestrator after a `RequestClipboardContent`)
    /// that is ready to be pasted into the terminal.
    PasteText(String),
    /// Indicates that the terminal window has gained focus.
    FocusGained,
    /// Indicates that the terminal window has lost focus.
    FocusLost,
}

// --- Selection-related Enums and Structs ---

/// Defines the mode or shape of a text selection.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SelectionMode {
    /// Standard linear text selection, character by character, wrapping lines.
    Normal,
    /// Rectangular block selection, selecting a geometric block of cells.
    Block,
}

/// Represents the state of an active text selection within the terminal.
///
/// Coordinates are 0-based, where `(col, row)` refers to the
/// character cell at the given column and row.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SelectionState {
    /// The starting coordinate (column, row) of the selection.
    /// This is typically where the mouse button was pressed or selection began.
    pub start: (usize, usize),
    /// The current ending coordinate (column, row) of the selection.
    /// This is typically where the mouse is currently dragged or where selection ended.
    pub end: (usize, usize),
    /// The mode of selection (e.g., normal linear or block).
    pub mode: SelectionMode,
}

// --- Structs for Rendering Snapshots ---

/// Represents the visual state of the cursor for rendering.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CursorRenderState {
    /// 0-based column of the cursor's position on the screen.
    pub col: usize,
    /// 0-based row of the cursor's position on the screen.
    pub row: usize,
    /// Shape identifier for the cursor (e.g., block, underline, bar).
    /// The interpretation of this value is up to the renderer and configuration.
    pub shape: u16,
    /// Whether the cursor should be visible.
    pub is_visible: bool,
}

/// Represents a single line of cells in a `RenderSnapshot`.
#[derive(Debug, Clone, PartialEq)]
pub struct SnapshotLine {
    /// The glyphs (character and attributes) in this line.
    pub cells: Vec<Glyph>,
    /// Flag indicating if this line is considered dirty and needs rerendering.
    /// This is a hint for the renderer; the emulator's internal dirty tracking
    /// might be more granular.
    pub is_dirty: bool,
}

/// Represents the state of a text selection for rendering purposes.
/// This is part of the `RenderSnapshot`. Coordinates are 0-based (col, row).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SelectionRenderState {
    /// The starting coordinates (column, row) of the selection area for rendering.
    /// These coordinates should be normalized (e.g., start <= end).
    pub start_coords: (usize, usize),
    /// The ending coordinates (column, row) of the selection area for rendering.
    /// These coordinates should be normalized.
    pub end_coords: (usize, usize),
    /// The mode of selection (e.g., Normal, Block) being rendered.
    pub mode: SelectionMode,
}

/// A snapshot of the terminal's visual state intended for rendering.
///
/// This struct provides all necessary information for a renderer to draw
/// the terminal screen, including cell content, cursor state, and selection state.
#[derive(Debug, Clone, PartialEq)]
pub struct RenderSnapshot {
    /// Dimensions of the terminal grid (columns, rows).
    pub dimensions: (usize, usize),
    /// The content of each line in the terminal grid.
    pub lines: Vec<SnapshotLine>,
    /// Current state of the cursor for rendering. `None` if the cursor should not be rendered.
    pub cursor_state: Option<CursorRenderState>,
    /// Current state of the text selection for rendering. `None` if no active selection.
    pub selection_state: Option<SelectionRenderState>,
}

/// Defines the interface a terminal emulator must implement for interaction
/// with the renderer and orchestrator.
pub trait TerminalInterface {
    /// Returns the dimensions of the terminal grid (columns, rows).
    fn dimensions(&self) -> (usize, usize);

    /// Retrieves the glyph at the specified 0-based (column, row) coordinates.
    fn get_glyph(&self, x: usize, y: usize) -> Glyph;

    /// Creates a snapshot of the current terminal state for rendering.
    fn get_render_snapshot(&self) -> RenderSnapshot;

    /// Returns `true` if the terminal's cursor is currently set to be visible.
    fn is_cursor_visible(&self) -> bool;

    /// Returns the 0-based (column, row) position of the cursor on the screen.
    fn get_screen_cursor_pos(&self) -> (usize, usize);

    /// Retrieves and clears the set of dirty line indices.
    /// Lines are marked dirty when their content or appearance changes.
    fn take_dirty_lines(&mut self) -> Vec<usize>;

    /// Processes an `EmulatorInput` and returns an optional `EmulatorAction`
    /// if the input results in an action that requires external handling.
    fn interpret_input(&mut self, input: EmulatorInput) -> Option<EmulatorAction>;
}

// The actual implementation of TerminalInterface for TerminalEmulator is in src/term/emulator.rs
// This file defines the traits and shared data structures for the `term` module.

#[cfg(test)]
mod tests;
